name: Build and Deploy Vue App
on:
  push:
    branches:
      - main  # main branch'e push atıldığında çalışsın
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: hsyngkby
    steps:
    
      # 1. Kodu indir
      - uses: actions/checkout@v3
      
      # 2. Node.js yükle
      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Bağımlılıkları yükle
      - name: Install dependencies
        run: cd frontend && npm install

      # 4. Build et
      - name: Build Vue app
        run: cd frontend && npm run build

      # 5. Hosting'e deploy et (FTP örneği)
      - name: Upload to hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./frontend/dist/
