name: Build and Deploy Vue App

on:
  push:
    branches:
      - main
      - Developer

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    env:
      NODE_ENV: production
      API_URL: http://hsyngkby.com
    
    steps:
      
      - name: Deploy
        run: echo "Deploying to ${{ vars.DEPLOY_URL }}"
        
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: cd frontend && npm install
      
      - name: Build Vue app
        env:
          VITE_ADSENSE_CLIENT: ${{ secrets.ADSENSE_CLIENT_ID }}
          run: cd frontend && npm run build
      
      - name: Upload to hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/dist/
          server-dir: /public_html/
